# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo First Build Job
  - job: SecondJob
    steps:
    - bash: echo Second Build Job

- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeploy
    steps:
    - bash: echo DevDeploy

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeploy
    steps:
    - bash: echo QADeploy

- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeploy
    steps:
    - bash: echo ProdDeploy
